---
- name: Install Java (required for Jenkins)
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Create keyrings directory for Jenkins
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Jenkins GPG key
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | \
    gpg --dearmor -o /etc/apt/keyrings/jenkins.gpg
  args:
    creates: /etc/apt/keyrings/jenkins.gpg

- name: Add Jenkins apt repository
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/jenkins.gpg] \
    https://pkg.jenkins.io/debian-stable binary/" \
    > /etc/apt/sources.list.d/jenkins.list
  args:
    creates: /etc/apt/sources.list.d/jenkins.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Add user in docker 
  user:
    name: jenkins
    groups: docker
    append: true


